// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearHacker.png
var resourceKrankyBearHackerPngData []byte
var resourceKrankyBearHackerPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHacker.png",
	StaticContent: resourceKrankyBearHackerPngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}

//go:embed assets/images/KrankyBearNerd.png
var resourceKrankyBearNerdPngData []byte
var resourceKrankyBearNerdPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearNerd.png",
	StaticContent: resourceKrankyBearNerdPngData,
}
